routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

use App\Http\Middleware\Admin;

Route::group(['middleware' => 'web'], function () {

    //Route::get('tables', ['uses' => 'SelectTablesController@show', 'as' => 'select.tables']);

    // Route::get('login25', ['uses' => 'Auth\LoginController@showLoginForm', 'as' => 'login25']);


    Auth::routes();

    Route::get('loginAs/{login}', function($login) {
        if (\Auth::user()->isAdmin()) {
            Auth::guard()->login(\App\User::byLogin($login));
        }

        return redirect('/');
    });

});

// $middleware = ['web'];

// if (env('DEMO_INSTANCE')) {
//     $middleware[] = 'auth';
// }

    Route::get('/', 'HomeController@index');

    Route::get('/news', ['as' => 'news','uses' => 'NewsController@index']);
    Route::get('/news/{id}', ['as' => 'news','uses' => 'NewsController@show']);

    Route::get('/materials', ['as' => 'materials','uses' => 'MaterialController@index']);
    Route::get('/materials/{id}', ['as' => 'materials','uses' => 'MaterialController@show']);



Route::group(['middleware' => ['web', "auth"]], function () {

    Route::get('account/referral-data', ['as' => 'referralData', 'uses' => 'AccountController@showReferralData']);

    Route::get('account/referral-invited-users', ['as' => 'referralInvitedUsers', 'uses' => 'AccountController@showReferralInvitedUsers']);

    Route::get('account/history', ['as' => 'history', 'uses' => 'AccountController@showHistory' ]);

    Route::get('account/payment-data', ['as' => 'paymentData', 'uses' => 'AccountController@showPaymentData' ]);

    Route::get('account/edit-requisite-form', ['as' => 'paymentData', 'uses' => 'AccountController@showCreateUpdateRequisiteForm' ]);

    Route::post('account/update-requisite', ['as' => 'updateRequisite', 'uses' => 'AccountController@createUpdateRequisite']);

    Route::post('account/update-profile', ['as' => 'updateProfile', 'uses' => 'AccountController@updateProfile']);

    Route::post('account/withdraw-funds', ['as' => 'withdrawFunds', 'uses' => 'AccountController@withdrawFunds']);

    Route::post('account/tree', ['as' => 'see.tree', 'uses' => 'AccountController@showTree']);

    Route::get('account/{page}', ['as' => 'account', 'uses' => 'AccountController@showPage']);
});

Route::group(['middleware' => ['web', 'auth', 'admin'], 'as' => 'admin.'], function() {
        
    Route::get('admin/transaction/{id}/{status}', ['as' => 'approvePayment', 'uses' => 'Admin\TransactionApprovementController@setTransactionStatus']);
    // Подтверждение платежа
    Route::get('admin/user/{id}/approve-payment', ['as' => 'approvePayment', 'uses' => 'Admin\PaymentController@approvePayment']);
    Route::post('admin/user/set-payment', ['as' => 'setPayment', 'uses' => 'Admin\PaymentController@setPayment']);

    CRUD::resource('admin/page', 'Admin\PageCrudController');
    CRUD::resource('admin/news', 'Admin\NewsCrudController');
    CRUD::resource('admin/user', 'Admin\UserCrudController');
    CRUD::resource('admin/transaction', 'Admin\TransactionCrudController');
    CRUD::resource('admin/material', 'Admin\MaterialCrudController');
    CRUD::resource('admin/desk', 'Admin\DeskCrudController');
    
    Route::resource('admin/tables', 'Admin\TableController');
    
});

/*
     * Если шаблон маршрута может отработать по статически закрепленному пути,
     * его следует размещать ниже. Иначе контроллер статического пути не отравботает,
     * а контроллер по шаблону выдаст 404
     */
Route::get('/{slug}', 'PageController@show');

app/Http/Controllers/Admin/TableController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Table;
use Validator;

class TableController extends AdminMasterController
{
    
    public function index()
    {
        $tables = Table::all();
        return view("pages.tables.index")->with('tables', $tables);
    }

    
    public function create()
    {
        return $this->outputAdminView("pages.tables.create");
    }

    
    public function store(Request $request)
    {
        $data = $request->except('_token');

        $validator = Validator::make($data, [
            "name" => "required|string|min:5|max:200",
            "slug" => "required|string|alpha_num",
            "count" => "required|numeric",

            "count_home" => "required|numeric",
            "count_place_home" => "required|numeric",

            "y_lv_3" => "required|numeric",
            "y_lv_4" => "required|numeric",
            "y_lv_5" => "required|numeric",
            "y_lv_6" => "required|numeric",
            "y_lv_7" => "required|numeric",
            "y_lv_8" => "required|numeric",
            "y_lv_9" => "required|numeric",
            "y_lv_10" => "required|numeric",

            "description" => "required|string",
        ]);

        
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($data);
        }

        $table = Table::create([
            "name" => $data['name'],
            "slug" => $data["slug"],
            "active" => isset($data["active"]) ? true : false,
            "count" => $data["count"],

            "count_home" => $data["count_home"],
            "count_place_home" => $data["count_place_home"],

            "y_lv_3" => $data["y_lv_3"],
            "y_lv_4" => $data["y_lv_4"],
            "y_lv_5" => $data["y_lv_5"],
            "y_lv_6" => $data["y_lv_6"],
            "y_lv_7" => $data["y_lv_7"],
            "y_lv_8" => $data["y_lv_8"],
            "y_lv_9" => $data["y_lv_9"],
            "y_lv_10" => $data["y_lv_10"],

            "description" => $data["description"],
        ]);

        return redirect("admin/tables")->with("success", "Стол успешно создан!");
    }

    
    public function show($id)
    {
        $table = Table::findOrfail($id);
        return $this->outputAdminView("pages.tables.info", "table", $table);
    }

    
    public function edit($id)
    {
        $table = Table::find($id);

        // dd($id);
        return $this->outputAdminView("pages.tables.edit", "table", $table);
    }

    
    public function update(Request $request, $id)
    {
        $data = $request->except("_token", "_method");

        // dd($data);

        $validator = Validator::make($data, [
            "name" => "required|string|min:5|max:200",
            "slug" => "required|string|alpha_num",
            "count" => "required|numeric",

            "count_home" => "required|numeric",
            "count_place_home" => "required|numeric",

            "y_lv_3" => "required|numeric",
            "y_lv_4" => "required|numeric",
            "y_lv_5" => "required|numeric",
            "y_lv_6" => "required|numeric",
            "y_lv_7" => "required|numeric",
            "y_lv_8" => "required|numeric",
            "y_lv_9" => "required|numeric",
            "y_lv_10" => "required|numeric",

            "description" => "required|string",
        ]);

        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput($data);
        }

        $table = Table::findOrfail($id);

        $table->update([
            "name" => $data['name'],
            "slug" => $data["slug"],
            "active" => isset($data["active"]) ? true : false,
            "count" => $data["count"],

            "count_home" => $data["count_home"],
            "count_place_home" => $data["count_place_home"],

            "y_lv_3" => $data["y_lv_3"],
            "y_lv_4" => $data["y_lv_4"],
            "y_lv_5" => $data["y_lv_5"],
            "y_lv_6" => $data["y_lv_6"],
            "y_lv_7" => $data["y_lv_7"],
            "y_lv_8" => $data["y_lv_8"],
            "y_lv_9" => $data["y_lv_9"],
            "y_lv_10" => $data["y_lv_10"],

            "description" => $data["description"],
        ]);

        return redirect("admin/tables")->with("success", "Стол успешно обновлен!");
    }

    
    public function destroy($id)
    {

        $table = Table::findOrfail($id);

        if (count($table->users) > 0) {
            return redirect("admin/tables")->with("danger", "Стол не может быть удален!");
        }

        $table->delete();
        return redirect("admin/tables")->with("success", "Стол успешно удален!");
    }
}

resources/views/pages/tables/create.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Inline Charts
            <small>multiple types of charts</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Charts</a></li>
            <li class="active">Inline Charts</li>
        </ol>
    </section>
@endsection

@section('content')

    @include('includes.session_errors')


    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box box-info ">
                    <div class="box-header with-border">
                        <h3 class="box-title">Horizontal Form</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->

                    <form action="{{ route('admin.tables.store') }}" method="POST">
                        
                        {{ csrf_field() }}

                        <div class="box-body">

                            <div class="col-sm-5">
                                <div class="form-group">
                                    <label for="inputEmail3">Название стола</label>
                                    <input type="text" name="name" class="form-control" value="{{ old('name') }}" id="inputEmail3" placeholder="Название стола">
                                </div>
                            
                                {{-- <div class="form-group">
                                    <label for="inputPassword3">Префикс стола</label>
                                    <input type="text" name="slug" class="form-control" value="{{ old('slug') }}" id="inputPassword3" placeholder="Префикс стола например: table-2">
                                </div> --}}
                            
                                <label for="inputPassword3"> Количество участников</label>
                                <div class="input-group col-sm-12">
                                    <span class="input-group-addon">
                                        <input name="active" type="checkbox">
                                    </span>
                                    <input name="count" type="number" min="1" max="10" value="{{ old('number') }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Количество участников">
                                </div>




                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3"> Количество Домов</label>
                                    <input name="count_home" type="number" value="{{ old('count_home') }}" min="1" max="10" class="form-control col-sm-12"  id="inputPassword3" placeholder="Количество Домов">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3"> Количество мест в доме</label>
                                    <input name="count_place_home" type="number" value="{{ old('count_place_home') }}" min="1" max="10" class="form-control col-sm-12"  id="inputPassword3" placeholder="Количество мест в доме">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (3 урвень) </label>
                                    <input name="y_lv_3" type="number" value="{{ old('y_lv_3') }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (3 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (4 урвень) </label>
                                    <input name="y_lv_4" type="number" value="{{ old('y_lv_4') }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (4 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (5 урвень) </label>
                                    <input name="y_lv_5" type="number" value="{{ old('y_lv_5') }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (5 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (6 урвень) </label>
                                    <input name="y_lv_6" type="number" value="{{ old('y_lv_6') }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (6 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (7 урвень) </label>
                                    <input name="y_lv_7" type="number" value="{{ old('y_lv_7') }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (7 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда на (8 урвень) </label>
                                    <input name="y_lv_8" type="number" value="{{ old('y_lv_8') }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (8 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда на (9 урвень) </label>
                                    <input name="y_lv_9" type="number" value="{{ old('y_lv_9') }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (9 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда на (10 урвень) </label>
                                    <input name="y_lv_10" type="number" value="{{ old('y_lv_10') }}"   class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (10 урвень)">
                                </div>


                            </div>

                            <div class="col-sm-5">
                                <div class="form-group">
                                    <label for="inputEmail3">Правила стола</label>
                                    {{--  <input type="email" class="form-control" id="inputEmail3" placeholder="Email">  --}}
                                    <textarea name="description" class="form-control" id="desc" cols="30" rows="10" placeholder="Правило стола...">{{ old('description') }}</textarea>
                                </div>
                            </div>
                            
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{ redirect()->back() }}" class="btn btn-default">Назад</a>

                            <input type="submit" class="btn btn-info pull-right" value="Создать">
                            {{--  <bottom type="submit" class="btn btn-info pull-right">Создать</bottom>  --}}

                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>


@endsection

resources/views/pages/tables/edit.blade.php
@extends('backpack::layout')

@section('header')
    <section class="content-header">
        <h1>
            Inline Charts
            <small>multiple types of charts</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Charts</a></li>
            <li class="active">Inline Charts</li>
        </ol>
    </section>
@endsection

@section('content')

    
    @include('includes.session_errors')
    

    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box box-info ">
                    <div class="box-header with-border">
                        <h3 class="box-title">Horizontal Form</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->

                    <form action="{{ route('admin.tables.update', $table->id) }}" method="POST">
                        <input type="hidden" name="_method" value="PUT">
                        
                        {{ csrf_field() }}

                        <div class="box-body">

                            <div class="col-sm-5">
                                <div class="form-group">
                                    <label for="inputEmail3">Название стола</label>
                                    <input type="text" name="name" class="form-control" value="{{ $table->name }}" id="inputEmail3" placeholder="Название стола">
                                </div>
                            
                                <div class="form-group">
                                    <label for="inputPassword3">Префикс стола</label>
                                    <input type="text" name="slug" class="form-control" value="{{ $table->slug }}" id="inputPassword3" placeholder="Префикс стола например: table-2">
                                </div>
                            
                                <label for="inputPassword3"> Количество участников</label>
                                <div class="input-group col-sm-12">
                                    <span class="input-group-addon">
                                        <input name="active" type="checkbox" {{ ($table->active) ? 'checked' : 'null' }}>
                                    </span>
                                    <input name="count" type="number" min="1" max="10" value="{{ $table->count }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Количество участников">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3"> Количество Домов</label>
                                    <input name="count_home" type="number" min="1" max="10" value="{{ $table->count_home }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Количество Добов">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3"> Количество мест в доме</label>
                                    <input name="count_place_home" type="number" min="1" max="10" value="{{ $table->count_place_home }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Количество мест в доме">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (3 урвень) </label>
                                    <input name="y_lv_3" type="number" value="{{ $table->y_lv_3 }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (3 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (4 урвень) </label>
                                    <input name="y_lv_4" type="number" value="{{ $table->y_lv_4 }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (4 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (5 урвень) </label>
                                    <input name="y_lv_5" type="number" value="{{ $table->y_lv_5 }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (5 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (6 урвень) </label>
                                    <input name="y_lv_6" type="number" value="{{ $table->y_lv_6 }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (6 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда за (7 урвень) </label>
                                    <input name="y_lv_7" type="number" value="{{ $table->y_lv_7 }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (7 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда на (8 урвень) </label>
                                    <input name="y_lv_8" type="number" value="{{ $table->y_lv_8 }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (8 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда на (9 урвень) </label>
                                    <input name="y_lv_9" type="number" value="{{ $table->y_lv_9 }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (9 урвень)">
                                </div>

                                <div class="input-group col-sm-12">
                                    <br>
                                    <label for="inputPassword3">Награда на (10 урвень) </label>
                                    <input name="y_lv_10" type="number" value="{{ $table->y_lv_10 }}" class="form-control col-sm-12"  id="inputPassword3" placeholder="Укажите награду за (10 урвень)">
                                </div>



                            </div>

                            <div class="col-sm-5">
                                <div class="form-group">
                                    <label for="inputEmail3">Правила стола</label>
                                    {{--  <input type="email" class="form-control" id="inputEmail3" placeholder="Email">  --}}
                                    <textarea name="description" class="form-control" id="desc" cols="30" rows="10" placeholder="Правило стола...">{{ $table->description }}</textarea>
                                </div>
                            </div>
                            
                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <a href="{{ route('admin.tables.index') }}" class="btn btn-default">Назад</a>

                            <input type="submit" class="btn btn-info pull-right" value="Обновить">
                            {{--  <bottom type="submit" class="btn btn-info pull-right">Создать</bottom>  --}}

                        </div>
                        <!-- /.box-footer -->
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/pages/tables/index.blade.php
@extends('backpack::layout')


@section('header')
    <section class="content-header">


        <h1>
            Inline Charts
            <small>multiple types of charts</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Charts</a></li>
            <li class="active">Inline Charts</li>
        </ol>
    </section>
@endsection


@section('content')




<!-- /.row -->
<div class="row">
  <div class="col-xs-12">
    <div class="box">
        
      <div class="box-header">

        <div class="col-md-2">
            <a href="{{ url('admin/tables/create') }}" class="btn btn-block btn-success btn-sm">Создать новый стол.</a>
        </div><br><br><br>

        <h3 class="box-title">Responsive Hover Table</h3>
        
        <div class="box-tools">
          <div class="input-group input-group-sm" style="width: 150px;">
                
            <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

            
            <div class="input-group-btn">
              <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
            </div>
          </div>
        </div>
      </div>
      <!-- /.box-header -->
      <div class="box-body table-responsive no-padding">

        <table class="table table-bordered table-striped display dataTable table-hover">
            <tr>
                <th>Навание</th>
                <th>Префикс</th>
                {{-- <th>Кол-во Участников</th> --}}
                <th>Ссылка</th>
                <th>Активный</th>
                <th>Плавила</th>

                <th>Кол-во Домов</th>
                <th>Кол-во мест в доме</th>

                <th>Награда за (3 урвень)</th>
                {{-- <th>Укажите награду за (4 урвень)</th> --}}
                {{-- <th>Укажите награду за (5 урвень)</th> --}}
                {{-- <th>Укажите награду за (6 урвень)</th> --}}
                {{-- <th>Укажите награду за (7 урвень)</th> --}}
                {{-- <th>Укажите награду за (8 урвень)</th> --}}
                {{-- <th>Укажите награду за (9 урвень)</th> --}}
                <th>Награда за (10 урвень)</th>

                <th>Действи</th>
            </tr>
                
            @foreach ($tables as $table)

            {{--  {{ dd($table) }}  --}}

                <tr>
                    <td>{{ $table->name }}</td>
                    <td>{{ $table->slug }}</td>
                    {{-- <td>{{ count($table->users) }}</td> --}}
                    <td>{{ $table->slug }}</td>

                    <td>{{ $table->count_home }}</td>
                    <td>{{ $table->count_place_home }}</td>
                    <td>{{ $table->y_lv_3 }}</td>
                    {{-- <td>{{ $table->y_lv_4 }}</td> --}}
                    {{-- <td>{{ $table->y_lv_5 }}</td> --}}
                    {{-- <td>{{ $table->y_lv_6 }}</td> --}}
                    {{-- <td>{{ $table->y_lv_7 }}</td> --}}
                    {{-- <td>{{ $table->y_lv_8 }}</td> --}}
                    {{-- <td>{{ $table->y_lv_9 }}</td> --}}
                    <td>{{ $table->y_lv_10 }}</td>

                    <td>
                        <span class="label label-{{ ($table->active) ? 'success' : 'danger' }}">{{ $table->active }}</span>
                    </td>
                    <td>{{ str_limit($table->description, 20) }}</td>

                    <td>
                        <a class="btn btn-sm btn-info" href="{{ route('admin.tables.show', ['id' => $table->id]) }}">
                            <i class="fa fa-info-circle"></i> Подробнее</a>
                        <br>	

                        {{--  <a href="{{ url('admin/tables/' . $table->id . '/show') }}">wdawdawdawdawd</a>  --}}

                        

                        {{--  <a href="{{ url('admin/tables/' . $table->id) }}" style="margin: 2px 0;" data-id="{{ $table->id }}" class="btn btn-sm btn-danger">
                            DELETE
                        </a>  --}}

                        
                    </td>
                </tr>

            @endforeach
          
        </table>
      </div>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </div>
</div>

{{--  <script src="{{ asset('js') }}/ajax.js"></script>  --}}

@endsection